
modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="farmersdelight"
version="1.16.5-0.6.0"
displayName="Farmer's Bliss"
# updateJSONURL=""
displayURL="https://github.com/lunofe/FarmersBliss"
logoFile="logo.png"
logoBlur=false
credits="Chloe Dawn, Grimmauld, ConductiveFoam, simibubi, Jozufozu, bagel, Silk, SkySom, Eutro and many others!"
authors="vectorwing"
description="A fork of Farmer's Delight, made for Vampirism.co"
itemIcon="farmersdelight:stove"
configBackground="minecraft:textures/block/bricks.png"

[[dependencies.farmersdelight]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.farmersdelight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
